import type { CharacterDef } from '../types';

export const CHARACTERS: CharacterDef[] = [
  // ── TIER 1 — FREE / STARTER ──────────────────────────────────────────────────
  {
    id: 'apex',
    name: 'APEX',
    subtitle: 'Tech CEO / Exo-Suit',
    archetype: 'balanced',
    primaryColor: '#1a73e8',
    accentColor: '#4fc3f7',
    glowColor: '#00bcd4',
    stats: { health: 200, attack: 55, defense: 50, speed: 90 },
    specialName: 'Market Crash',
    specialDesc: 'Charges gauntlets and fires a bolt of electric energy forward',
    superName: 'System Override',
    superDesc: 'Full exo-suit activation: 5-second armor mode with enhanced speed and damage',
    icon: '⚡',
    unlockCost: 0,
    unlockLevel: 1,
    lore: 'Former Silicon Valley CEO who bankrolled an illegal exo-suit program. Now he fights to prove machines have no soul — only power.',
    rarity: 'common',
  },
  {
    id: 'venom',
    name: 'VENOM',
    subtitle: 'Street Racer / Drifter',
    archetype: 'rushdown',
    primaryColor: '#e53935',
    accentColor: '#ff6f00',
    glowColor: '#ff5722',
    stats: { health: 175, attack: 60, defense: 40, speed: 130 },
    specialName: 'Burnout',
    specialDesc: 'Lightning-fast slide kick that covers the full screen',
    superName: 'Nitro Overdrive',
    superDesc: 'Full-screen blur dash through the opponent 6 times, each hit faster than the last',
    icon: '🔥',
    unlockCost: 0,
    unlockLevel: 1,
    lore: 'Raised on midnight street races in Miami. Lost everything to a rival crew and now burns through every fight like it\'s his last lap.',
    rarity: 'common',
  },

  // ── TIER 2 — 500g ────────────────────────────────────────────────────────────
  {
    id: 'titan',
    name: 'TITAN',
    subtitle: 'Pro Athlete / Powerhouse',
    archetype: 'powerhouse',
    primaryColor: '#388e3c',
    accentColor: '#b2ff59',
    glowColor: '#76ff03',
    stats: { health: 250, attack: 80, defense: 65, speed: 65 },
    specialName: 'Overdrive',
    specialDesc: 'Armored super punch — absorbs hits and sends opponent flying',
    superName: 'Unstoppable',
    superDesc: '10-second full invincibility mode; every hit does double damage',
    icon: '💪',
    unlockCost: 500,
    unlockLevel: 1,
    lore: 'Disqualified Olympic athlete who turned to underground fighting. He doesn\'t just win fights — he ends careers.',
    rarity: 'common',
  },
  {
    id: 'ghost',
    name: 'GHOST',
    subtitle: 'Parkour / Free Runner',
    archetype: 'trickster',
    primaryColor: '#7b1fa2',
    accentColor: '#ce93d8',
    glowColor: '#e040fb',
    stats: { health: 175, attack: 55, defense: 35, speed: 120 },
    specialName: 'Phase Shift',
    specialDesc: 'Teleports behind the opponent and strikes from the shadows',
    superName: 'Phantom Army',
    superDesc: 'Spawns 3 ghost clones that attack simultaneously from all angles',
    icon: '👻',
    unlockCost: 500,
    unlockLevel: 1,
    lore: 'Grew up invisible to the world, living in the walls between buildings. Now she makes sure everyone sees what they\'re missing.',
    rarity: 'common',
  },

  // ── TIER 3 — 1,500g ──────────────────────────────────────────────────────────
  {
    id: 'reaper',
    name: 'REAPER',
    subtitle: 'Assassin / Shadow Killer',
    archetype: 'assassin',
    primaryColor: '#212121',
    accentColor: '#ff1744',
    glowColor: '#d50000',
    stats: { health: 160, attack: 75, defense: 30, speed: 135 },
    specialName: 'Death Mark',
    specialDesc: 'Marks target — next hit within 3s deals triple damage',
    superName: 'Final Execution',
    superDesc: 'Teleports behind opponent and lands 15 critical slashes in 2 seconds',
    icon: '☠️',
    unlockCost: 1500,
    unlockLevel: 5,
    lore: 'A ghost from a black-ops program who faked his own death. He fights to remind governments that their secrets never stay buried.',
    rarity: 'rare',
  },
  {
    id: 'oracle',
    name: 'ORACLE',
    subtitle: 'Hacker / Digital Sorcerer',
    archetype: 'zoner',
    primaryColor: '#00bcd4',
    accentColor: '#80deea',
    glowColor: '#18ffff',
    stats: { health: 180, attack: 50, defense: 45, speed: 100 },
    specialName: 'Data Breach',
    specialDesc: 'Fires a tracking data projectile that homes in on the opponent',
    superName: 'System Crash',
    superDesc: 'Hacks the arena: disables opponent\'s special moves for 10 seconds',
    icon: '💻',
    unlockCost: 1500,
    unlockLevel: 5,
    lore: 'She hacked the fight registration server at age 14. Now she uses code as a weapon and the arena as her terminal.',
    rarity: 'rare',
  },
  {
    id: 'steel',
    name: 'STEEL',
    subtitle: 'Military / Weapons Expert',
    archetype: 'balanced',
    primaryColor: '#607d8b',
    accentColor: '#b0bec5',
    glowColor: '#90a4ae',
    stats: { health: 220, attack: 65, defense: 60, speed: 80 },
    specialName: 'Tactical Roll',
    specialDesc: 'Invincible dash cancel into immediate counter-strike',
    superName: 'Full Arsenal',
    superDesc: 'Pulls every weapon from his loadout: grenade, knife, shotgun blast in one fluid chain',
    icon: '🪖',
    unlockCost: 1500,
    unlockLevel: 5,
    lore: 'Dishonorably discharged after going off-mission to save civilians. Now he fights his own war by his own rules.',
    rarity: 'rare',
  },
  {
    id: 'blaze',
    name: 'BLAZE',
    subtitle: 'Pyromancer / Fire Dancer',
    archetype: 'rushdown',
    primaryColor: '#ff6d00',
    accentColor: '#ffea00',
    glowColor: '#ff9100',
    stats: { health: 185, attack: 70, defense: 35, speed: 110 },
    specialName: 'Inferno Step',
    specialDesc: 'Leaves a trail of fire while dashing — opponents who cross it burn',
    superName: 'Solar Flare',
    superDesc: 'Erupts into a full-screen pillar of flame for 3 seconds',
    icon: '🌋',
    unlockCost: 1500,
    unlockLevel: 6,
    lore: 'Born in a wildfire. Survived when nobody else did. She doesn\'t just fight — she burns everything that gets in her way.',
    rarity: 'rare',
  },

  // ── TIER 4 — 3,000g ──────────────────────────────────────────────────────────
  {
    id: 'kraken',
    name: 'KRAKEN',
    subtitle: 'Deep Sea / Leviathan',
    archetype: 'tank',
    primaryColor: '#006064',
    accentColor: '#4dd0e1',
    glowColor: '#00e5ff',
    stats: { health: 320, attack: 85, defense: 80, speed: 50 },
    specialName: 'Tidal Crush',
    specialDesc: 'Massive water slam that hits the entire screen width',
    superName: 'The Abyss Calls',
    superDesc: 'Summons the deep — drowns opponent in a water prison for 4 seconds while dealing continuous damage',
    icon: '🦑',
    unlockCost: 3000,
    unlockLevel: 10,
    lore: 'Emerged from an underwater research facility that should never have been built. He carries the ocean\'s rage in every swing.',
    rarity: 'rare',
  },
  {
    id: 'tempest',
    name: 'TEMPEST',
    subtitle: 'Storm Caller / Wind Monk',
    archetype: 'zoner',
    primaryColor: '#5c6bc0',
    accentColor: '#c5cae9',
    glowColor: '#7986cb',
    stats: { health: 190, attack: 58, defense: 48, speed: 115 },
    specialName: 'Gale Force',
    specialDesc: 'Pushes opponent to wall with a sustained wind blast',
    superName: 'Eye of the Storm',
    superDesc: 'Creates a tornado around self — any hit opponent is caught and slammed 8 times',
    icon: '🌪️',
    unlockCost: 3000,
    unlockLevel: 10,
    lore: 'A wandering monk who mastered breath to the point of weaponizing air itself. The winds obey. Opponents don\'t.',
    rarity: 'rare',
  },
  {
    id: 'void_king',
    name: 'VOID',
    subtitle: 'Dimensional Rift Walker',
    archetype: 'trickster',
    primaryColor: '#311b92',
    accentColor: '#7c4dff',
    glowColor: '#651fff',
    stats: { health: 195, attack: 68, defense: 42, speed: 118 },
    specialName: 'Rift Step',
    specialDesc: 'Opens a portal — exits anywhere on screen behind the opponent',
    superName: 'Dimension Collapse',
    superDesc: 'Collapses the arena into a void pocket for 6 seconds; gravity inverts',
    icon: '🌀',
    unlockCost: 3000,
    unlockLevel: 10,
    lore: 'He walked into a rift to save a child and came back... different. The dimensions folded into him. Now he uses them like a second skin.',
    rarity: 'epic',
  },
  {
    id: 'scorpio',
    name: 'SCORPIO',
    subtitle: 'Venomous / Desert Predator',
    archetype: 'assassin',
    primaryColor: '#f9a825',
    accentColor: '#fffde7',
    glowColor: '#ffd600',
    stats: { health: 170, attack: 72, defense: 38, speed: 125 },
    specialName: 'Venom Sting',
    specialDesc: 'Poison on hit — 8 damage per second for 5 seconds',
    superName: 'Death\'s Embrace',
    superDesc: 'Full-body venom injection combo: 20 stings in 3 seconds, each applying poison',
    icon: '🦂',
    unlockCost: 3000,
    unlockLevel: 11,
    lore: 'Ran the black market in Riyadh before the fights found him. He\'s patient, precise, and never misses his mark.',
    rarity: 'epic',
  },

  // ── TIER 5 — 6,000g ──────────────────────────────────────────────────────────
  {
    id: 'akuma',
    name: 'AKUMA',
    subtitle: 'Dark Martial Artist / Demon Within',
    archetype: 'powerhouse',
    primaryColor: '#b71c1c',
    accentColor: '#ff8a80',
    glowColor: '#ff1744',
    stats: { health: 210, attack: 90, defense: 55, speed: 95 },
    specialName: 'Raging Demon',
    specialDesc: 'Grabs opponent and delivers a 10-hit hell combo with no chance to escape',
    superName: 'Satsui No Hado',
    superDesc: 'Unleashes the killing intent — triples attack for 8 seconds, causes screen to go dark red',
    icon: '👹',
    unlockCost: 6000,
    unlockLevel: 15,
    lore: 'He chose power over humanity. Every fight risks crossing the point of no return. He doesn\'t care — he welcomes it.',
    rarity: 'epic',
  },
  {
    id: 'cyborg',
    name: 'CYBORG',
    subtitle: 'Half-Machine / Augmented Soldier',
    archetype: 'balanced',
    primaryColor: '#37474f',
    accentColor: '#00e5ff',
    glowColor: '#00b0ff',
    stats: { health: 230, attack: 72, defense: 68, speed: 85 },
    specialName: 'Overclock',
    specialDesc: 'Doubles attack speed for 4 seconds',
    superName: 'Termination Protocol',
    superDesc: 'Activates kill-mode: 12-hit combo with laser eyes, rocket fist, and EMP slam',
    icon: '🤖',
    unlockCost: 6000,
    unlockLevel: 15,
    lore: 'Left for dead on a battlefield. Rebuilt with stolen military tech. He doesn\'t feel pain — only processing lag.',
    rarity: 'epic',
  },
  {
    id: 'valkyrie',
    name: 'VALKYRIE',
    subtitle: 'Norse Warrior / Chosen of Odin',
    archetype: 'tank',
    primaryColor: '#5d4037',
    accentColor: '#ffcc02',
    glowColor: '#ffab00',
    stats: { health: 270, attack: 78, defense: 75, speed: 72 },
    specialName: 'Shield Bash',
    specialDesc: 'Counter-attack: absorbs a hit and responds with a devastating shield slam',
    superName: 'Valhalla Charge',
    superDesc: 'Calls upon the fallen — a spectral army rushes the screen for 4 seconds',
    icon: '⚔️',
    unlockCost: 6000,
    unlockLevel: 15,
    lore: 'Chosen at birth to escort the worthy. She decided she\'d be worthy herself first. The gods disagreed. She didn\'t care.',
    rarity: 'epic',
  },
  {
    id: 'shadow_lotus',
    name: 'LOTUS',
    subtitle: 'Shadow Clan / Kunoichi',
    archetype: 'assassin',
    primaryColor: '#880e4f',
    accentColor: '#f48fb1',
    glowColor: '#f06292',
    stats: { health: 165, attack: 78, defense: 32, speed: 140 },
    specialName: 'Petal Storm',
    specialDesc: 'Throws 8 razor petals that track the opponent',
    superName: 'Thousand Cuts',
    superDesc: 'Becomes invisible, then lands 25 cuts in 2 seconds from all directions',
    icon: '🌸',
    unlockCost: 6000,
    unlockLevel: 16,
    lore: 'Last of the Lotus clan, betrayed by the very order she protected. Her kills are as beautiful as they are final.',
    rarity: 'epic',
  },

  // ── TIER 6 — LEGENDARY (12,000g) ────────────────────────────────────────────
  {
    id: 'golem',
    name: 'GOLEM',
    subtitle: 'Ancient Stone Guardian',
    archetype: 'tank',
    primaryColor: '#4e342e',
    accentColor: '#a1887f',
    glowColor: '#8d6e63',
    stats: { health: 400, attack: 95, defense: 100, speed: 40 },
    specialName: 'Tectonic Slam',
    specialDesc: 'Slams fists into ground — creates 3 rock pillars that erupt under opponent',
    superName: 'Mountain\'s Wrath',
    superDesc: 'Transforms into pure stone for 10 seconds — immune to all damage, reflects 50% back',
    icon: '🗿',
    unlockCost: 12000,
    unlockLevel: 25,
    lore: 'Carved from the mountain by a dying civilization and animated by their last breath. He fights to honor a world long gone.',
    rarity: 'legendary',
  },
  {
    id: 'phoenix',
    name: 'PHOENIX',
    subtitle: 'Fire God / Eternal Rebirth',
    archetype: 'balanced',
    primaryColor: '#e65100',
    accentColor: '#ffcc02',
    glowColor: '#ff6d00',
    stats: { health: 215, attack: 82, defense: 58, speed: 108 },
    specialName: 'Rebirth Flame',
    specialDesc: 'Once per match: revives with 50 HP when KO\'d',
    superName: 'Solar Annihilation',
    superDesc: 'Transforms into a giant phoenix — dives across the entire stage dealing 200 damage',
    icon: '🦅',
    unlockCost: 12000,
    unlockLevel: 25,
    lore: 'She has died 11 times in the arena. Each time she returns stronger. Opponents who beat her once always lose the rematch.',
    rarity: 'legendary',
  },
  {
    id: 'shogun',
    name: 'SHOGUN',
    subtitle: 'Feudal Warlord / Death God',
    archetype: 'powerhouse',
    primaryColor: '#1a237e',
    accentColor: '#7986cb',
    glowColor: '#3949ab',
    stats: { health: 240, attack: 95, defense: 70, speed: 78 },
    specialName: 'Iaijutsu',
    specialDesc: 'Lightning-speed sheath draw — if it hits, deals 80 damage instantly',
    superName: 'Sengoku Storm',
    superDesc: 'Unleashes 1000 years of warrior souls — full screen katana barrage for 5 seconds',
    icon: '🏯',
    unlockCost: 12000,
    unlockLevel: 25,
    lore: 'His bloodline has fought since the first war. He refuses to let the age of warriors end.',
    rarity: 'legendary',
  },

  // ── TIER 7 — SECRET (30,000g + Level 50) ──────────────────────────────────
  {
    id: 'god_emperor',
    name: 'GOD EMPEROR',
    subtitle: '???',
    archetype: 'balanced',
    primaryColor: '#ffd700',
    accentColor: '#fff9c4',
    glowColor: '#ffff00',
    stats: { health: 350, attack: 100, defense: 100, speed: 100 },
    specialName: 'Divine Strike',
    specialDesc: 'A strike that bypasses all defensive abilities — pure damage',
    superName: 'Absolute Dominion',
    superDesc: 'Reduces opponent to 1 HP instantly, then locks controls for 3 seconds',
    icon: '👑',
    unlockCost: 30000,
    unlockLevel: 50,
    lore: '???',
    rarity: 'secret',
  },
];

export function getCharacter(id: string): CharacterDef {
  return CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
}

export function getCharactersByRarity(rarity: CharacterDef['rarity']): CharacterDef[] {
  return CHARACTERS.filter((c) => c.rarity === rarity);
}

export function getUnlockedCharacters(level: number, currency: number): CharacterDef[] {
  return CHARACTERS.filter((c) => c.unlockLevel <= level || c.unlockCost <= currency);
}
